import {FormEvent,useState} from 'react'
import {multipartBody,signedFetch,signedRequest} from '../api'
type Asset={id:string;version:number;kind:string}
type Item={id:string;product_name:string;customer_email:string;status:string;created_at:string;assets:Asset[]}
export function Admin(){
 const[keyId,setKeyId]=useState(sessionStorage.bbKeyId||''),[secret,setSecret]=useState(''),[items,setItems]=useState<Item[]>([]),[error,setError]=useState('')
 async function load(e?:FormEvent){e?.preventDefault();try{sessionStorage.bbKeyId=keyId;const r=await signedFetch('/v1/manual-tasks?limit=100',keyId,secret);setItems(r.items);setError('')}catch(x){setError(x instanceof Error?x.message:'Bağlantı hatası')}}
 async function quote(id:string){const value=prompt('Fiyat (TL)');if(!value)return;await signedFetch(`/v1/manual-tasks/${id}/quote`,keyId,secret,{method:'POST',body:JSON.stringify({amount_minor:Math.round(Number(value)*100),currency:'TRY',expires_at:new Date(Date.now()+7*86400000).toISOString()})});load()}
 async function patchStatus(id:string,status:string){await signedFetch(`/v1/manual-tasks/${id}`,keyId,secret,{method:'PATCH',body:JSON.stringify({status})});load()}
 async function schedule(id:string){const value=prompt('Teslim tarihi (YYYY-AA-GG)');if(!value)return;await signedFetch(`/v1/manual-tasks/${id}/schedule`,keyId,secret,{method:'POST',body:JSON.stringify({delivery_due_at:new Date(`${value}T18:00:00+03:00`).toISOString()})});load()}
 async function refs(item:Item){const response=await signedRequest(`/v1/manual-tasks/${item.id}/references.zip`,keyId,secret);if(!response.ok)throw new Error('Görseller indirilemedi');const url=URL.createObjectURL(await response.blob()),a=document.createElement('a');a.href=url;a.download=`${item.product_name}-referanslar.zip`;a.click();URL.revokeObjectURL(url)}
 async function upload(item:Item,files:FileList|null){if(!files?.length)return;const mapped:Record<string,File>={};for(const file of [...files]){const ext=file.name.split('.').pop()?.toLowerCase();if(ext&&['glb','usdz','blend'].includes(ext))mapped[ext]=file}const multi=multipartBody(mapped);await signedFetch(`/v1/manual-tasks/${item.id}/assets`,keyId,secret,{method:'POST',headers:{'Content-Type':multi.contentType},body:multi.body});load()}
 async function publish(item:Item){const version=Math.max(...item.assets.map(x=>x.version));await signedFetch(`/v1/manual-tasks/${item.id}/publish`,keyId,secret,{method:'POST',body:JSON.stringify({version})});load()}
 return <main><section className="card"><h1>Modelleme yönetimi</h1>{!items.length&&<form className="admin-login" onSubmit={load}><label>API anahtar kimliği<input value={keyId} onChange={e=>setKeyId(e.target.value)}/></label><label>API gizli anahtarı<input type="password" value={secret} onChange={e=>setSecret(e.target.value)}/></label><button>Giriş yap</button></form>}{error&&<p className="error">{error}</p>}{items.length>0&&<div className="table">{items.map(x=><article key={x.id}><div><strong>{x.product_name}</strong><small>{x.customer_email} · {new Date(x.created_at).toLocaleDateString('tr-TR')}</small></div><span className="status-pill">{x.status}</span><div className="actions"><button className="secondary" onClick={()=>refs(x)}>Görseller</button>{x.status==='submitted'&&<button onClick={()=>quote(x.id)}>Fiyatlandır</button>}{x.status==='paid'&&<button onClick={()=>schedule(x.id)}>Tarih ver</button>}{['scheduled','awaiting_modeling'].includes(x.status)&&<button onClick={()=>patchStatus(x.id,'modeling')}>Modellemeye başla</button>}{['modeling','revision_required'].includes(x.status)&&<label className="upload-button">Model yükle<input type="file" multiple accept=".glb,.usdz,.blend" onChange={e=>upload(x,e.target.files)}/></label>}{x.status==='awaiting_review'&&x.assets.length>0&&<button onClick={()=>publish(x)}>Yayınla</button>}</div></article>)}</div>}</section></main>
}
